run_id:
  header: "Run ID"
  formatter: "truncate"
  max_length: 52

total_steps:
  header: "Steps"
  formatter: "integer"

max_lr:
  header: "Max LR"
  formatter: "scientific"
  precision: 2

min_lr:
  header: "Min LR"
  formatter: "scientific"
  precision: 2

initial_lr:
  header: "Init LR"
  formatter: "scientific"
  precision: 2

final_lr:
  header: "Final LR"
  formatter: "scientific"
  precision: 2

initial_train_loss:
  header: "Init Loss"
  formatter: "decimal"
  precision: 3

final_train_loss:
  header: "Final Loss"
  formatter: "decimal"
  precision: 3

min_train_loss:
  header: "Min Loss"
  formatter: "decimal"
  precision: 3

max_tokens:
  header: "Max Tokens"
  formatter: "comma"

max_epoch:
  header: "Max Epoch"
  formatter: "integer"

loss_improvement:
  header: "Loss Î”"
  formatter: "decimal"
  precision: 3

Model_Size:
  header: "Model"
  formatter: "string"

Dataset_Tokens:
  header: "Dataset"
  formatter: "string"

model_size_m:
  header: "Model Size"
  formatter: "string"

dataset_total_m:
  header: "Dataset Tokens"
  formatter: "string"

learning_rate:
  header: "Learning Rate"
  formatter: "scientific"
  precision: 2

olmes_acc:
  header: "OLMES Acc"
  formatter: "decimal"
  precision: 3

pile_perplexity:
  header: "Pile PPL"
  formatter: "decimal"
  precision: 1

arc_challenge:
  header: "ARC Challenge"
  formatter: "decimal"
  precision: 3

mmlu_acc:
  header: "MMLU Acc"
  formatter: "decimal"
  precision: 3

train_loss:
  header: "Train Loss"
  formatter: "decimal"
  precision: 3

metric:
  header: "Metric"
  formatter: "string"

available:
  header: "Available"
  formatter: "integer"

total:
  header: "Total"
  formatter: "integer"

coverage:
  header: "Coverage"
  formatter: "string"
